### ISSUE TITLE
tests/test_inotify_buffer.py tests fail in 1-core-VM

### ISSUE THREAD

**Issue by bmwiedemann** [gorakhargosh/watchdog#823] opened 2021-07-29 13:04 UTC
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that our `python-watchdog-2.1.3` package failed 1 test when running in a 1-core-VM (usually this happens due to differences in scheduling/timing)

### To reproduce

maybe run tests as `taskset 1 pytest`

or on Debian or openSUSE run
```
osc checkout openSUSE:Factory/python-watchdog && cd $_
osc build --vm-type=kvm --noservice --clean -j1 standard
```

### Actual behavior

4 test errors

```
 =========================== short test summary info ============================
 ERROR tests/test_inotify_buffer.py::test_move_to - AssertionError: assert not...
 ERROR tests/test_inotify_buffer.py::test_move_internal - AssertionError: asse...
 ERROR tests/test_inotify_buffer.py::test_move_internal_batch - AssertionError...
 ERROR tests/test_inotify_buffer.py::test_close_should_terminate_thread - Asse...
 =========== 100 passed, 6 skipped, 1 deselected, 4 errors in 29.42s ============
```

You can find the full build log with errors at https://rb.zq1.de/temp/python-watchdog-j1-buildlog.txt

**Comment by BoboTiG** [comment] 2021-07-29 13:45
Attached the log file for history.
[python-watchdog-j1-buildlog.txt](https://github.com/gorakhargosh/watchdog/files/6900935/python-watchdog-j1-buildlog.txt)

---

The issue is not about 1-core, but about `OSError: [Errno 9] Bad file descriptor`. It is not the first time someone reported such issue :thinking:

**Comment by BoboTiG** [comment] 2021-07-29 14:15
I close that issue as duplicate of #805. Thanks for the report @bmwiedemann  :)

**Closed by BoboTiG** 2021-07-29 14:15 UTC
Labels: PR welcome :), inotify
