### ISSUE TITLE
Discern end of copy process?

### ISSUE THREAD

**Issue by jgoodleaf** [gorakhargosh/watchdog#567] opened 2019-05-08 21:23 UTC
On Windows, I need to watch a directory for the appearance of a new item. Now this is straightforward, but the catch here is that the new item will be a directory hierarchy. In other words, someone will copy a new tree into this location. I will not be in a position to know anything about the number of files and directories in the new tree, nor their size (and they could be sizable, up to 100GB). But I don't want to take any action  until AFTER all the files have been copied. 

Is there an elegant way to know for sure when the last part of the tree have finished copying? There are hacky solution where I could watch for the calculated size of the folder to stop growing, but I'm not in love with that approach... I'd like to control the initial copy, since that would give me some leverage, but that's out of the question at the moment....

**Comment by RobertWang** [comment] 2019-09-10 16:51
+1

**Comment by BoboTiG** [comment] 2019-10-28 13:29
Closing as duplicate of #313.

**Closed by BoboTiG** 2019-10-28 13:29 UTC
Labels: duplicate
