### ISSUE TITLE
Deprecation warning on bricks.py

### ISSUE THREAD

**Issue by mosesontheweb** [gorakhargosh/watchdog#584] opened 2019-09-22 17:34 UTC
Hi,

just discovered this notice:

`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

A fix might be great. Regards, Thomas

**Comment by BoboTiG** [comment] 2019-09-25 20:23
Hello,

Thanks, I close it as a duplicate of #583.

**Closed by BoboTiG** 2019-09-25 20:23 UTC
