### ISSUE TITLE
BUG on latest version on Windows

### ISSUE THREAD

**Issue by gaetan1903** [gorakhargosh/watchdog#937] opened 2022-12-31 11:41 UTC
```shell
$ watchmedo auto-restart --patterns="*.py;langs.json" --recursive -- python -c "import core;core.ampalibe.init.run()" 
failed to create process
```

with the old version it works, but with the last no

**Comment by BoboTiG** [comment] 2022-12-31 12:35
Could be a duplicate of #935.

**Comment by gaetan1903** [comment] 2022-12-31 18:50
when it's released ? or i install via master branch ?

**Comment by BoboTiG** [comment] 2023-01-01 09:43
Right now, the release process is ongoing :)

**Comment by BoboTiG** [comment] 2023-01-01 09:54
Can you confirm the [version 2.2.1](https://github.com/gorakhargosh/watchdog/releases/tag/v2.2.1) works for you, please?

**Closed** 2023-01-04 12:13 UTC

**Comment by gaetan1903** [comment] 2023-01-04 18:34
i confirm, it works fine with the latest version

Thank you
