### ISSUE TITLE
Adding callbacks after instantiating FileSystemEventHandler  doesn't fire the callback.

### ISSUE THREAD

**Issue by unique1o1** [gorakhargosh/watchdog#832] opened 2021-08-22 16:45 UTC
**OS**: Pop!_OS 20.04 LTS
**Python version**: 3.9.5
**Watchdog version**: 2.1.4

Adding callbacks (`on_deleted`, `on_created`...) after instantiating `FileSystemEventHandler` class(and its subclasses) will not fire the respective callback when a event is trigger    

For example:
This Works
```python
class myEventHandler(RegexMatchingEventHandler):
    def on_created(self,event):
        print(f" created!")

    def on_deleted(self,event):
        print(f"deleted")

    def on_modified(self,event):
        print(f"modified")

    def on_moved(self,event):
        print(f"moved")
my_event_handler = myEventHandler(
    [".*"], None, False, False
)
path = "."
my_observer = Observer()
my_observer.schedule(my_event_handler, path, recursive=True)
my_observer.start()
try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    my_observer.stop()
    my_observer.join()
```

This doesn't
```python
def on_created(self,event):
    print(f" created!")
def on_deleted(self,event):
    print(f"deleted")
def on_modified(self,event):
    print(f"modified")
def on_moved(self,event):
    print(f"moved")

path = "."
my_event_handler = RegexMatchingEventHandler(
    [".*"], None, False, False
)
my_event_handler.on_created = on_created
my_event_handler.on_deleted = on_deleted
my_event_handler.on_modified = on_modified
my_event_handler.on_moved = on_moved

my_observer = Observer()
my_observer.schedule(my_event_handler, path, recursive=True)
my_observer.start()
try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    my_observer.stop()
    my_observer.join()
```

changes from the PR #814 seems to be the reason for the issue.

EDIT: Sorry if this is not the preferred way of doing things. I just started using watchdog and many articles on the web used this approach and mine was not working, which got me scratching my head hard. I tried the above code on the older version i.e (2.1.3) and it worked.

**Comment by BoboTiG** [comment] 2021-08-23 09:25
Thanks, it is a duplicate of #830. I am closing that one and focus on #830.

**Closed by BoboTiG** 2021-08-23 09:25 UTC
