### ISSUE TITLE
Using WatchDog to Spawn Processes

### ISSUE THREAD

**Issue by MikeOcc** [gorakhargosh/watchdog#388] opened 2016-11-30 18:45 UTC
I am unclear as to how to access the file and directory names after they have been added/modified.  I need that information to be able to spawn independent python processes.

**Comment by DonyorM** [comment] 2016-12-01 06:47
Do you mean you need to know the paths to the files? Or just the names of the files?

**Comment by MikeOcc** [comment] 2016-12-13 02:14
Actually, my issue has morphed.  I am able to use watchdog to monitor file creation and trigger processes, but when I attach a directory in docker using the -v command, it doesn't seem to see or detect the file changes.

**Comment by DonyorM** [comment] 2016-12-13 02:29
What operating system/observer are you using. I believe some of them cannot cross filesystems.

**Comment by rrzaripov** [comment] 2019-11-04 21:41
@BoboTiG I think we can close this issue, because not additional information for it reproduce issue was be appended.

**Closed** 2019-11-05 09:17 UTC
Labels: Incomplete (need more info)
