### ISSUE TITLE
Watchdog lose efficacy after deleting the watching path

### ISSUE THREAD

**Issue by renlf** [gorakhargosh/watchdog#419] opened 2017-09-03 13:56 UTC
We have use the watchdog to build up our file tamper proof system. While watching the illegal tamper operation, the system will restore the original ones. But we have found out that the watchdog would lose efficacy after deleting the watching path. 
How to fix this issue. Because our system have to keep watching the folder even after removing it.

**Comment by danilobellini** [comment] 2018-08-29 00:03
You mean, you want to keep watching a path even if gets removed in the middle of the process? Either you should use a polling watcher, or you should watch its parent directory with the (default) OS-specific observer filtering the path in the application code, I think the latter should be the preferred approach, unless the parent directory is something like the root directory.

Anyway, I'm not sure what had been your use case, not even what's the operating system running your code. Can you show a way for us to reproduce your *efficacy* issue?

**Comment by rrzaripov** [comment] 2019-11-04 21:17
@BoboTiG I think we can close this issue, because not additional information for it reproduce issue was be appended.

**Closed** 2019-11-05 09:17 UTC
Labels: Incomplete (need more info)
