### ISSUE TITLE
Installation fails on Linux (watchdog latest version 0.10.0, python 3.6)

### ISSUE THREAD

**Issue by artempronevskiy** [gorakhargosh/watchdog#619] opened 2020-01-28 15:36 UTC
```
$ python3 -m pip install watchdog

Downloading https://files.pythonhosted.org/packages/01/01/cc9b2fd111e19687dd42155f066718bccb414c8a728eb7df0b229742caf7/watchdog-0.10.0.tar.gz (94kB)
  Complete output from command python setup.py egg_info:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-xb_pe9d_/watchdog/setup.py", line 86, in <module>
      changelog = f.read()
    File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 63: ordinal not in range(128)
```

**Comment by tpazderka** [comment] 2020-01-28 16:38
This seems to be fixed on master, so I guess a bugfix should be published to PyPi ?

**Comment by krbullock** [comment] 2020-01-28 22:19
Same issue here. Our builds are failing on CircleCI (docker image based on Ubuntu).

**Comment by BoboTiG** [comment] 2020-01-29 07:27
We are looking for another bugfix (#617 and #618) before releasing a new version. Hopefully this is will quick.

**Comment by BoboTiG** [comment] 2020-01-30 00:04
Duplicate of #615.

**Closed** 2020-01-30 00:03 UTC
