### ISSUE TITLE
on_deleted does not raise recursively events for each file, dir

### ISSUE THREAD

**Issue by cr3a7ure** [gorakhargosh/watchdog#561] opened 2019-04-02 11:18 UTC
On Windows 10, python 3.6

When I add files, on_created fires for every file/directory recursively.
But when i remove a folder, on_deleted does not fire, except for the parent directory.
Edit:
It emits a FileDeletedEvent instead of DirDeletedEvent

**Comment by BoboTiG** [comment] 2019-06-11 22:39
Yes, this is a known limitation of the windows API. (duplicate of #429)

**Closed by BoboTiG** 2019-06-11 22:39 UTC
