### ISSUE TITLE
Modifed event triggered twice

### ISSUE THREAD

**Issue by jcouyang** [gorakhargosh/watchdog#93] opened 2012-03-02 15:37 UTC
if I copy and paste a file on OSX lion
it triggered created event once and modified event twice
should it be just trigger once modified event?

`
INFO:root:Created file: /Users/ouyangjichao/BoxSync/rename/testwatchdog.py
INFO:root:Modified file: /Users/ouyangjichao/BoxSync/rename/testwatchdog.py
INFO:root:Modified file: /Users/ouyangjichao/BoxSync/rename/testwatchdog.py
`

**Comment by travcunn** [comment] 2017-12-11 14:50
Perhaps it would be helpful to do a `stat` to check when a file was last modified to avoid triggering twice, especially if it's unavoidable from OS-specific implementation.

**Comment by RRSR** [comment] 2017-12-25 10:11
The same issue still exists i.e. on creation of a new file the 'modified' event is called twice.

**Comment by naveenjafer** [comment] 2017-12-25 10:25
@RRSR A workaround to this which I am following is based on a suggestion by @travcunn 
`import time
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
import sys
import subprocess
import os
old = 0
mainPath = os.getcwd()
class Watcher:
    DIRECTORY_TO_WATCH = sys.argv[1]
    def __init__(self):
        self.observer = Observer()

    def run(self):
        event_handler = Handler()
        self.observer.schedule(event_handler, self.DIRECTORY_TO_WATCH, recursive=True)
        self.observer.start()
        try:
            while True:
                time.sleep(5)
        except:
            self.observer.stop()
            print("Error")

        self.observer.join()


class Handler(FileSystemEventHandler):

    @staticmethod
    def on_any_event(event):
        global old
        if event.is_directory:
            return None

        elif event.event_type == 'created':
            # Take any action here when a file is first created.
            filename = sys.argv[2]
            print("Received created event - %s." % event.src_path)


        elif event.event_type == 'modified':
            filename = sys.argv[2]
            statbuf = os.stat(filename)
            new = statbuf.st_mtime
            print(str(new) + " is new")
            print(str(old) + " is old")
            if (new - old) > 0.5:
                print("Received modified event - %s." % event.src_path) 
                # Do the action you would like to do here.
            old = new

if __name__ == '__main__':
    w = Watcher()
    w.run()
`
The 2 events that are fired are fired just after each other, with a few milliseconds at most(at least in my case). Hope this helps

**Comment by leon-vv** [comment] 2019-01-22 13:37
I also have this issue, and I think I found the problem.

In `src/watchdog/observers/inotify.py` line 162 we have:
```Python
elif event.is_modify:
    cls = DirModifiedEvent if event.is_directory else FileModifiedEvent
    self.queue_event(cls(src_path))
```

which uses the `is_modify` property. Which comes from `src/watchdog/observers/inotify_c.py`:

```Python
@property
def is_modify(self):
    return self._mask & InotifyConstants.IN_MODIFY > 0
```
Notice that `IN_MODIFY` is used as the definition of file modification. But the Inotify documentation (http://inotify.aiken.cz/?section=inotify&page=faq&lang=en) says:

>  What is the difference between IN_MODIFY and IN_CLOSE_WRITE?
The IN_MODIFY event is emitted on a file content change (e.g. via the write() syscall) while IN_CLOSE_WRITE occurs on closing the changed file. It means each change operation causes one IN_MODIFY event (it may occur many times during manipulations with an open file) whereas IN_CLOSE_WRITE is emitted only once (on closing the file). 

> Is it better to use IN_MODIFY or IN_CLOSE_WRITE?
It varies from case to case. Usually it is more suitable to use IN_CLOSE_WRITE because if emitted the all changes on the appropriate file are safely written inside the file. The IN_MODIFY event needn't mean that a file change is finished (data may remain in memory buffers in the application). On the other hand, many logs and similar files must be monitored using IN_MODIFY - in such cases where these files are permanently open and thus no IN_CLOSE_WRITE can be emitted. 

So the solution is, I think, to expose both the `IN_MODIFY` and the `IN_CLOSE_WRITE` event in the Python interface. This way both use cases can be supported.

**Comment by anvesh1212** [comment] 2019-06-20 06:22
Is this issue resolved? because I'm using watchdog 0.9.0, when i modify a .txt file through notepad in windows 10, on_modify methods gets call once or twice randomly.

**Comment by Endogen** [comment] 2019-06-20 19:19
@anvesh1212 no, not resolved

**Comment by anvesh1212** [comment] 2019-06-21 06:17
@Endogen any alternative solution? and when can we expect it to be resolved?

**Comment by Endogen** [comment] 2019-06-21 08:46
@anvesh1212 I don't think it will ever be fixed. This issue is open till 2012. I go with the workaround that @naveenjafer posted on 25 Dec 2017.

**Comment by MalcolmOdd** [comment] 2019-10-29 23:45
@anvesh1212 On Windows 10 it might be a slightly different issue. The library will provide a different implementation (WindowsApiObserver) when it detects that the platform is Windows. I was able to reproduce the issue 100% of the time on Windows 10 with the default import:
    from watchdog.observers import Observer
However I no longer reproduce it by selecting the generic implementation:
    from watchdog.observers import PollingObserver as Observer
This could be used as a workaround, although this class may not be guaranteed to be suitable in the future.

**Comment by danielloader** [comment] 2019-10-30 20:18
So I did some digging and found watchgod, and it handles this better albeit in a different way, opened 4 files in vscode, made a change and did save all running the following example:

```
from watchgod import watch

for changes in watch('.'):
    print(changes)
```

resulting output:

```
python .\test.py 
{(<Change.modified: 2>, '.\\test\\test_file-d.txt'), (<Change.modified: 2>, '.\\test\\test_file-c.txt'), (<Change.modified: 2>, '.\\test\\test_file-a.txt'), (<Change.modified: 2>, '.\\test\\test_file-b.txt')}
```

It's definitely different but it's not duplicated so from my POV that's something I can work with - last thing I want to do is add a FIFO queue and dequeue system in to deduplicate these things prior to execution of a function on the file.

**Closed** 2021-01-15 09:22 UTC
Labels: fsevents-c
