### ISSUE TITLE
 tricks.yaml location?

### ISSUE THREAD

**Issue by bitsofinfo** [gorakhargosh/watchdog#358] opened 2016-05-31 21:25 UTC
trying `watchmedo tricks-from /path/to/tricks.yaml` ... but it appears that watchmedo doesn't execute any of the tricks unless the `tricks.yaml` exists in the same directory the watchmedo command is launched. Why is this? Or am I missing something here. 

I have a need to monitor a directory w/ custom tricks, but NOT have the tricks.yaml file live in the directory I am monitoring...

**Comment by DonyorM** [comment] 2016-11-23 03:47
From the homepage:

> The directory containing the tricks.yaml file will be monitored. Each trick class is initialized with its corresponding keys in the tricks.yaml file as arguments and events are fed to an instance of this class as they arrive.

So no, you can't do what you're wanting. I'm not sure the exact reasons, since I didn't code that aspect of the code, if you're willing you could consider trying to add the patch yourself.

**Comment by rrzaripov** [comment] 2019-11-04 21:47
@BoboTiG I think we can close this issue, because not additional information for it reproduce issue was be appended.

**Comment by danilobellini** [comment] 2019-11-06 01:07
An example would help here. I would try `cat /path/to/tricks.yaml | watchmedo tricks-from` in a Linux/BSD/MacOS environment to do what had been asked, although I see no reason for requiring the path to be always the current working directory (i.e., it looks like a bug).

**Comment by rrzaripov** [comment] 2019-11-06 06:55
@danilobellini thank you for explaining, in this case this is really look like bug, I need yo investigate.

**Closed** 2019-12-12 15:51 UTC
Labels: Incomplete (need more info)
