### ISSUE TITLE
auto restart in watchdog==2.1.6

### ISSUE THREAD

**Issue by pirate-pete** [gorakhargosh/watchdog#855] opened 2021-11-10 20:47 UTC
Hey dawgs,

There appears to be an issue with v2.1.6 specific to having a `auto-restart` flag when initiating `watchdog` using the following command:

`watchmedo auto-restart -- python -u some_python_file.py`

Here is the error from the console:
![image](https://user-images.githubusercontent.com/75047122/141190666-1f10f93d-0c43-40d2-976a-82659f64d424.png)

Reverting to `2.1.5` fixed the issue. Hopefully the issue will be resolved in the upcoming release.

Cheers,

**Comment by BoboTiG** [comment] 2021-11-11 07:26
Maybe related to #836, would you mind to have a quick look @lorenzobn 🙏 ?

**Comment by dtcooper** [comment] 2021-11-11 20:06
Did some poking around, and maybe this will help.

I traced it somewhat to [line 174 `watchdog/tricks/__init__.py`](https://github.com/gorakhargosh/watchdog/blob/57e80a50/src/watchdog/tricks/__init__.py#L172-L174),

```python
def start(self):
    # windows doesn't have setsid
    self.process = subprocess.Popen(self.command, preexec_fn=getattr(os, 'setsid', None))
```

Where `self.command` is `auto-restart` and NOT the command to watch in Python 3.9 (works on Python 3.10 for some reason).

Also getting this error, but with `shell-command` as well. Perhaps related.

```
$ watchmedo shell-command --patterns='*.py' --command='echo "${watch_src_path}'
# on save of a .py file
/bin/sh: 1: shell-command: not found
/bin/sh: 1: shell-command: not found
/bin/sh: 1: shell-command: not found
```

**Comment by lorenzobn** [comment] 2021-11-12 08:03
> 
> 
> Maybe related to #836, would you mind to have a quick look @lorenzobn 🙏 ?

I'll do it as soon as I can 👍

**Comment by lorenzobn** [comment] 2021-11-20 17:27
I tried to reproduce the errors reported by @pirate-pete and @dtcooper on watchdog 2.16. Unfortunately, I wasn't able to replicate them. 
Could you please write a step-by-step description, with general information such as your OS and python version, so that I can reproduce the error?

**Comment by ildarworld** [comment] 2021-11-20 17:34
> I tried to reproduce the errors reported by @pirate-pete and @dtcooper on watchdog 2.16. Unfortunately, I wasn't able to replicate them.
> Could you please write a step-by-step description, with general information such as your OS and python version, so that I can reproduce the error?

that's can be easily reproduced in docker by using **python:3.9.6-slim** image

in docker-compose file I have tried like this:

`command: sh -c "watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python main.py"
`

**Comment by lorenzobn** [comment] 2021-11-20 17:58
@ildarworld Do you have a screenshot or something about the error? Is it a `FileNotFoundException` similar to the image provided by @pirate-pete the kind of error you get?

**Comment by dtcooper** [comment] 2021-11-22 22:56
Here are specific steps to repro using Docker on Debian Bullseye (`debian:bullseye-slim`) which bundles Python 3.9.2. Confusingly, I could not reproduce this in the `python:3.9.2-slim` container

Using docker, enter the container needed to reproduce.

```bash
# Debian version that is broken
docker run --rm -it debian:bullseye-slim bash
```

In that container using bash, execute the following to reproduce

```bash
# Create a dir to work in
mkdir -p /issue-855-repro
cd /issue-855-repro

# Install Python, pip and latest watchmedo
apt-get update
apt-get install -y --no-install-recommends python3 python3-pip
pip install watchdog[watchmedo]

# Reproduce bug
echo 'print("Reproduce issue 855")' > test.py
watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python test.py
```

Yields,

```python-traceback
Traceback (most recent call last):
  File "/usr/local/bin/watchmedo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/watchdog/watchmedo.py", line 641, in main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/watchdog/watchmedo.py", line 625, in auto_restart
    handler.start()
  File "/usr/local/lib/python3.9/dist-packages/watchdog/tricks/__init__.py", line 174, in start
    self.process = subprocess.Popen(self.command, preexec_fn=getattr(os, 'setsid', None))
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
```

I've tested this on both `--platform linux/amd64` and `--platform linux/arm64/v8` args for `docker run`. (I personally use an Apple M1 machine, but also repro'd on an amd64 machine.)

Hope that helps!

**Comment by BoboTiG** [comment] 2021-12-15 13:43
Hmm I cannot reproduce either using watchmedo 2.1.6 and the current dev branch (2.1.7), using Python 3.9.9 :thinking:

**Comment by sopi20** [comment] 2021-12-22 10:34
Hi, I have the same problem with 2.1.6., reverting to 2.1.5 makes it work again (probably related to getting rid of argh dependency in 2.1.6, and somewhat different behaviour with current parser).

`Traceback (most recent call last):
  File "/usr/local/bin/watchmedo", line 33, in <module>
    sys.exit(load_entry_point('watchdog==2.1.6', 'console_scripts', 'watchmedo')())
  File "/usr/local/lib/python3.9/site-packages/watchdog/watchmedo.py", line 641, in main
    args.func(args)
  File "/usr/local/lib/python3.9/site-packages/watchdog/watchmedo.py", line 625, in auto_restart
    handler.start()
  File "/usr/local/lib/python3.9/site-packages/watchdog/tricks/__init__.py", line 174, in start
    self.process = subprocess.Popen(self.command, preexec_fn=getattr(os, 'setsid', None))
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in _init_
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'auto-restart'`

I also had some issue with option arguments that did not expect any value to expect it in 2.1.6 (probably due to the same reason):

`usage: watchmedo auto-restart [-h] [-d directory] [-p PATTERNS]
                              [-i IGNORE_PATTERNS] [-D] [-R]
                              [--interval TIMEOUT] [--signal SIGNAL]
                              [--debug-force-polling DEBUG_FORCE_POLLING]
                              [--kill-after KILL_AFTER]
                              command [arg ...]
watchmedo auto-restart: error: argument --debug-force-polling: expected one argument`

Python version is 3.9.8, OS is FreeBSD, command line I'm using is:

`watchmedo auto-restart --directory=<directory> --pattern=<directory> --signal=SIGTERM --debug-force-polling -- celery <celery_arguments>`

**Comment by kozlovzxc** [comment] 2022-01-11 06:14
Any help needed to reproduce this?

Error
```
Traceback (most recent call last):
  File "/Users/kozlovzxc/.local/share/virtualenvs/app-QadN2i4i/bin/watchmedo", line 8, in <module>
    sys.exit(main())
  File "/Users/kozlovzxc/.local/share/virtualenvs/app-QadN2i4i/lib/python3.9/site-packages/watchdog/watchmedo.py", line 641, in main
    args.func(args)
  File "/Users/kozlovzxc/.local/share/virtualenvs/app-QadN2i4i/lib/python3.9/site-packages/watchdog/watchmedo.py", line 625, in auto_restart
    handler.start()
  File "/Users/kozlovzxc/.local/share/virtualenvs/app-QadN2i4i/lib/python3.9/site-packages/watchdog/tricks/__init__.py", line 174, in start
    self.process = subprocess.Popen(self.command, preexec_fn=getattr(os, 'setsid', None))
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'auto-restart'
```

Python version
```
3.9.8
```

Watchmedo version
```
"index": "pypi",
"version": "==2.1.6"
```

**Comment by taleinat** [comment] 2022-05-12 19:42
This may be cause by using "command" both as the name for the argparse sub-parsers destination ([watchmedo.py line 71](https://github.com/gorakhargosh/watchdog/blob/030fb0aba3bf8ac90650003a4e86cc8951f2f08e/src/watchdog/watchmedo.py#L71)) as well as the command to run ([line 524](https://github.com/gorakhargosh/watchdog/blob/030fb0aba3bf8ac90650003a4e86cc8951f2f08e/src/watchdog/watchmedo.py#L524)).

Note that the same is true for `watchmedo shell-command`.

**Comment by BoboTiG** [comment] 2022-05-13 12:55
> I also had some issue with option arguments that did not expect any value to expect it in 2.1.6 (probably due to the same reason):
> 
> ```
> usage: watchmedo auto-restart [-h] [-d directory] [-p PATTERNS]    
>                               [-i IGNORE_PATTERNS] [-D] [-R]    
>                               [--interval TIMEOUT] [--signal SIGNAL]    
>                               [--debug-force-polling DEBUG_FORCE_POLLING]    
>                               [--kill-after KILL_AFTER]    
>                               command [arg ...]    
> watchmedo auto-restart: error: argument --debug-force-polling: expected one argument
> ```

Fixed with #887.

**Comment by BoboTiG** [comment] 2022-05-13 13:11
I am still unable to reproduce the original issue with Python 3.10.4 and watchdog 2.1.7 (and unreleased).

**Comment by BoboTiG** [comment] 2022-05-13 13:21
OK I finally reproduced on Python 3.9.8. What whatever magical reason, the bug is not triggered on Python 3.10. Working on a fix, thanks to @taleinat fir the hint ;)

**Closed** 2022-05-13 13:34 UTC
Labels: bug, PR welcome :)

**Comment by BoboTiG** [comment] 2022-05-13 13:39
Could you confirm that the version from the `master` branch does fix your issues, please?
If so, I'll publish a new release ASAP.
