### ISSUE TITLE
Watchdog on Mac OS not tracking new dirs when recursively listening for changes

### ISSUE THREAD

**Issue by fabioz** [gorakhargosh/watchdog#706] opened 2020-11-29 12:40 UTC
The test below shows the issue... 

It works properly on Windows but on Mac it fails saying that the only change it found is the creation of `my0.txt` (when it should've also found the change for the creation of the `dir_rec` and `dir_rec/my1.txt`).

```
def test_watchdog_recursive(tmpdir):
    import watchdog
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler
    import os.path

    class Handler(FileSystemEventHandler):
        def __init__(self):
            FileSystemEventHandler.__init__(self)
            self.changes = []

        def on_any_event(self, event):
            self.changes.append(os.path.basename(event.src_path))

    handler = Handler()
    observer = Observer()

    watches = []
    watches.append(observer.schedule(handler, str(tmpdir), recursive=True))

    try:
        observer.start()
        time.sleep(0.1)

        tmpdir.join("my0.txt").write("foo")
        tmpdir.join("dir_rec").mkdir()
        tmpdir.join("dir_rec").join("my1.txt").write("foo")

        expected = {"dir_rec", "my0.txt", "my1.txt"}
        timeout_at = time.time() + 5
        while not expected.issubset(handler.changes) and time.time() < timeout_at:
            time.sleep(0.2)

        if not expected.issubset(handler.changes):
            raise AssertionError(
                f"Did not find expected changes. Found: {handler.changes}"
            )
    finally:
        for watch in watches:
            observer.unschedule(watch)
        observer.stop()
```

**Comment by BoboTiG** [comment] 2020-12-01 07:20
Thank you for the test case @fabioz :)
I'll dig into it ASAP.

**Comment by BoboTiG** [comment] 2020-12-02 20:40
Just curious: what version of watchdog? Did it work before?

**Comment by mwdiers** [comment] 2020-12-02 23:08
I am having a lot of problems with FileSystemEventHandler as well. It works the first time, and then entirely stops working No events detected.

Also, when I move a file into a watched path, I do not get an event from the file I moved, but only from .DS_Store.

**Comment by fabioz** [comment] 2020-12-03 10:40
> Just curious: what version of watchdog? Did it work before?

I'm testing with the latest released version (`v0.10.4`). I'm not sure if it worked before or not (I know it works when using the fallback to use the `kqueue` -- but that's not really feasible on my case as it requires too many file descriptors).

**Comment by BoboTiG** [comment] 2020-12-03 10:43
Do you mind trying with 0.10.3 🙏 ?

**Comment by kevin-bates** [comment] 2020-12-04 18:46
FWIW, I'm just (today) checking out watchdog and, using 0.10.4 (MacOS BigSur), could not get _any_ event notifications (regardless of recursion, files, or directory changes).  Switching to 0.10.3 works immediately!

Thank you for this package - it looks like what I need!

**Comment by BoboTiG** [comment] 2020-12-04 19:28
Duplicate of #702.

**Closed by BoboTiG** 2020-12-04 19:28 UTC
Labels: bug, fsevents

**Comment by fabioz** [comment] 2020-12-07 13:14
Sorry about the delay... I just tested it here and as reported, it really works with 0.10.3.
